services:
  postgres:
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: easy-finance
    volumes:
      - ./data:/var/lib/postgresql/data